#docker-compose up -d
#docker-compose logs -f

version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins
    restart: always
    container_name: jenkins
    ports:
      - "10081:8080"
      - "50000:50000"
    volumes:
      - "./data:/var/jenkins_home"