#docker-compose up -d
#docker-compose logs -f

version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:2.151
    container_name: jenkins
    networks:
      - net
    user: "root"
    restart: always
    ports:
      - 9000:8080
    environment:
      - JAVA_OPTS="-Duser.timezone=Asia/Shanghai"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/jenkins_home:rw
      - ./backup:/var/jenkins_backup:rw
# 网络配置
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16