#docker-compose up -d
#docker-compose logs -f

version: '3.7'
services:
  gitlab:
    image: "twang2218/gitlab-ce-zh:11.0.2"
    restart: always
    hostname: 'gitlab'
    ports:
      - "10022:22"
      - "10080:10080"
      # postgresql 端口
      - "5432:5432"
    volumes:
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/log:/var/log/gitlab
      - ./gitlab/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # 仓库路径, 填写宿主机的域名或 IP
        external_url 'http://192.168.xxx.xxx:10080'
        # 调整工作进程数减小内存占用，最小为 2
        unicorn['worker_processes'] = 2
        gitlab_rails['time_zone'] = 'Asia/Shanghai'

        # 邮箱配置
        gitlab_rails['gitlab_email_from'] = '<your_email>'
        gitlab_rails['gitlab_email_display_name'] = '<your_email_name>'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.163.com'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "<your_email_account>"
        gitlab_rails['smtp_password'] = "<your_email_password>"
        gitlab_rails['smtp_domain'] = 'smtp.163.com'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false

        # 数据库配置
        gitlab_rails['db_host'] = '127.0.0.1'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"

        postgresql['listen_address'] = '0.0.0.0'
        postgresql['port'] = 5432
        postgresql['md5_auth_cidr_addresses'] = %w()
        postgresql['trust_auth_cidr_addresses'] = %w(0.0.0.0/0)
        postgresql['sql_user'] = "gitlab"
        postgresql['sql_user_password'] = Digest::MD5.hexdigest "gitlab" << postgresql['sql_user']

        # 备份设置-保留7天
        gitlab_rails['backup_keep_time'] = 604800
      GITLAB_BACKUPS: "daily"
      GITLAB_SIGNUP: "true"
      GITLAB_ROOT_PASSWORD: "lb80h&85"
      GITLAB_GRAVATAR_ENABLED: "true"